version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  
  build-machine:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run: sudo apt-get update
  
  build-mac:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: echo "Hello MacOS"
  
  build-win:
    executor: win/server-2022
    steps:
      - run: Write-Host 'Hello, Windows'

workflows:
  build-docker-workflow:
    jobs:
      - build-docker
      - build-machine
      - build-mac
      - build-win