version: 2.1

parameters:
  condition-workflow:
    type: boolean
    default: true

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - when:
          condition:
            or:
            #- << pipeline.parameters >>
            #- equal: [ master, <<pipeline.git.branch >> ]
              #- << Tester.parameters >>
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run: echo "I am on main"

  conditional-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  my-workflow:
    jobs:
      - my-job

conditional-workflow:
    when:
      condition:
       and:
        - << pipeline.parameters >>
        - equal: [ master, << pipeline.parameters.my-parameter >> ]
    jobs:
      - conditional-job