version: 2.1

orbs: 
  win: circleci/windows@4.1.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"

    build:
      macos:
        xcode: 14.0.0
      steps:
      - run: echo "Run this MAC Op Sys Job"

    build:
      executor: win/server-2022
      steps:
        -run: Write-Host 'Whats up, Windows'

workflows:
  build-docker-workflow:
    jobs:
      - build